name: deploy

on:
  push:
    branches: [main]

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: auth
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: kubeconfig
        run: aws eks update-kubeconfig --name gp-cluster

      - name: deploy
        run: helm upgrade --install hello
